### ISSUE TITLE
Rate-Limiting - (intermediate value) is not iterable

### ISSUE THREAD

**Issue by mickelluiten** [athombv/node-homey-oauth2app#107]
When sending a API request and response is 429 ( Request is rate limited ) homey webapp shows undefined error message instead of custom warning message.

![image](https://github.com/user-attachments/assets/19db1120-e1fa-4a36-8d8a-d83c324209c3)

overiding : onHandleResult

```
  async onHandleResult({
    result,
    status,
    statusText,
    headers,
  }) {
    return [result, status, statusText];
  }
```
device : 
```
 const [result, status, statusText] = await this.oAuth2Client.updateCharacteristicSimple(this.HomeyGatewayDeviceId, 'climateControl', 'onOffMode', await this.getKeyByValue(translateOnoff, value)).catch(this.error);
      if (status === 204) {
        this.log(`**** onOffMode to DaikinCloud sets to: ${await this.getKeyByValue(translateOnoff, value)} for id: ${this.HomeyGatewayDeviceId} ****`);
      } else if (status === 429) {
        this.setWarning(statusText);
      }
```

Debug log : 
```
2024-12-14T11:22:09.385Z [log] [DaikinApp] [dbg] [DaikinOAuth2Client] [c:default] [s:3fe03872-b485-47b2-8f45-a3d26d9489ea] [req] Content-Type: application/json
2024-12-14T11:22:09.385Z [log] [DaikinApp] [dbg] [DaikinOAuth2Client] [c:default] [s:3fe03872-b485-47b2-8f45-a3d26d9489ea] [req] {"value":"off"}
2024-12-14T11:22:09.447Z [log] [DaikinApp] [dbg] [DaikinOAuth2Client] [c:default] [s:3fe03872-b485-47b2-8f45-a3d26d9489ea] [res] { ok: false, status: 429, statusText: 'Too Many Requests' }
2024-12-14T11:22:09.447Z [log] [DaikinApp] [dbg] [DaikinOAuth2Client] [c:default] [s:3fe03872-b485-47b2-8f45-a3d26d9489ea] Request is rate limited
2024-12-14T11:22:09.448Z [err] [ManagerDrivers] [Driver:air_2_air_heatpump] [Device:d959d286-cfcb-496e-9ba5-256ebe4d5f60] OAuth2Error: Rate Limited
    at DaikinOAuth2Client.onRequestResponse (/app/node_modules/homey-oauth2app/lib/OAuth2Client.js:789:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DaikinDevice.onCapabilityonoff (/app/drivers/air_2_air_heatpump/device.js:360:44)
    at async DaikinDevice._onSetCapabilityValue (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:167:5)
```

**Comment by mickelluiten** [comment]
Sorry my fault,  no issue here
